language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: librsvg
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - librsvg2-dev
      - librsvg2-bin
      - libwebp-dev
      - libicu-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
