language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: librsvg
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      r_check_args: ""
    - r: 3.6
      os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - librsvg2-dev
      - librsvg2-bin
      - libwebp-dev
      - libicu-dev
      - libmagick++-dev
