language: r
cache: packages
latex: false

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.3
      brew_packages: librsvg
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - librsvg2-dev
      - librsvg2-bin
      - libwebp-dev
      - libicu-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
