language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx # Sierra
      osx_image: xcode8.2
      brew_packages: librsvg
      latex: false
    - os: osx # El Capitan
      osx_image: xcode8
      disable_homebrew: true
      latex: false
    - os: osx # Yosemite
      osx_image: beta-xcode6.4
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - librsvg2-dev
      - librsvg2-bin
      - libwebp-dev
      - libicu-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
